# Generated by Django 5.1.7 on 2025-03-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_transacao_data_alter_transacao_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
